version: "3.9"

services:
  api:
    image: 127.0.0.1:5000/api
    ports:
      - "3000:8000"
    deploy:
      mode: replicated
      replicas: 2
  chart:
    image: 127.0.0.1:5000/chart_image
    ports:
      - "8000:8001"
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - api
